[package]
name = "draft-template"
version = "0.0.1"
entrypoint = "draft-template.typ"
authors = ["Benjamin Doran"]
license = "MIT"
description = "Basic template for drafts including theorems and proofs"
repository = "https://github.com/BenjaminDoran/bens-typst-templates"
keywords = [
    "template"
]
categories = ["layout", "utility"]
compiler = "0.13.0"

[tool.packager]
paths = ["draft-template.typ", "LICENSE", "README.md"]